import type { MetricDefinition, MetricKey } from './types';

export const metricCatalog: Record<MetricKey, MetricDefinition> = {
  bpSystolic: {
    key: 'bpSystolic',
    label: 'АД систолическое',
    shortLabel: 'АД сист.',
    unit: 'мм рт.ст.',
    group: 'vitals',
    normalRange: [90, 130],
    higherIsBetter: false,
    decimals: 0,
  },
  bpDiastolic: {
    key: 'bpDiastolic',
    label: 'АД диастолическое',
    shortLabel: 'АД диаст.',
    unit: 'мм рт.ст.',
    group: 'vitals',
    normalRange: [60, 85],
    higherIsBetter: false,
    decimals: 0,
  },
  cigarettes: {
    key: 'cigarettes',
    label: 'Выкуренные сигареты',
    shortLabel: 'Сигареты',
    unit: 'шт/день',
    group: 'lifestyle',
    normalRange: [0, 0],
    higherIsBetter: false,
    decimals: 0,
  },
  kcal: {
    key: 'kcal',
    label: 'Калорийность рациона',
    shortLabel: 'Ккал',
    unit: 'ккал/день',
    group: 'lifestyle',
    normalRange: [1800, 2400],
    higherIsBetter: false,
    decimals: 0,
  },
  steps: {
    key: 'steps',
    label: 'Пройденные шаги',
    shortLabel: 'Шаги',
    unit: 'шагов/день',
    group: 'lifestyle',
    normalRange: [6000, 10000],
    higherIsBetter: true,
    decimals: 0,
  },
  activityMinutes: {
    key: 'activityMinutes',
    label: 'Физическая активность',
    shortLabel: 'Активность',
    unit: 'мин/день',
    group: 'lifestyle',
    normalRange: [30, 60],
    higherIsBetter: true,
    decimals: 0,
  },
  waterLiters: {
    key: 'waterLiters',
    label: 'Выпито воды',
    shortLabel: 'Вода',
    unit: 'л/день',
    group: 'lifestyle',
    normalRange: [1.5, 2],
    higherIsBetter: true,
    decimals: 1,
  },
  stressLevel: {
    key: 'stressLevel',
    label: 'Уровень стресса',
    shortLabel: 'Стресс',
    unit: 'баллов из 10',
    group: 'lifestyle',
    normalRange: [0, 4],
    higherIsBetter: false,
    decimals: 0,
  },
  hb: {
    key: 'hb',
    label: 'Гемоглобин (Hb)',
    shortLabel: 'Hb',
    unit: 'г/л',
    group: 'labs',
    normalRange: [120, 160],
    higherIsBetter: true,
    decimals: 0,
  },
  ferritin: {
    key: 'ferritin',
    label: 'Ферритин',
    shortLabel: 'Ферритин',
    unit: 'мкг/л',
    group: 'labs',
    normalRange: [20, 250],
    higherIsBetter: true,
    decimals: 0,
  },
  lymphocytes: {
    key: 'lymphocytes',
    label: 'Лимфоциты крови',
    shortLabel: 'Лимфоциты',
    unit: '%',
    group: 'labs',
    normalRange: [20, 40],
    higherIsBetter: true,
    decimals: 1,
  },
};

export const metricKeys = Object.keys(metricCatalog) as MetricKey[];
